# Colab notebook or tutorial
### [How to run PyTorch with GPU and CUDA 8.0 support on Google Colab](https://www.dlology.com/blog/how-to-run-pytorch-with-gpu-and-cuda-92-support-on-google-colab/)

In [ ]:
!nvidia-smi

Sun Nov 29 07:22:09 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.38       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   34C    P0    24W / 300W |      0MiB / 16130MiB |      0%      Default |
|                               |                      |                 ERR! |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
!cat /etc/*-release

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic


## Install Cuda 9.1
(https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1710&target_type=deblocal)

In [ ]:
!wget https://developer.nvidia.com/compute/cuda/9.1/Prod/local_installers/cuda-repo-ubuntu1704-9-1-local_9.1.85-1_amd64

--2020-11-29 07:22:14--  https://developer.nvidia.com/compute/cuda/9.1/Prod/local_installers/cuda-repo-ubuntu1704-9-1-local_9.1.85-1_amd64
Resolving developer.nvidia.com (developer.nvidia.com)... 152.199.16.29
Connecting to developer.nvidia.com (developer.nvidia.com)|152.199.16.29|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://developer.download.nvidia.com/compute/cuda/9.1/secure/Prod/local_installers/cuda-repo-ubuntu1704-9-1-local_9.1.85-1_amd64.deb?WkPGzPsRxBBT_nBljiVleNNiWH7s74QrdAQ15DlR83zbRNLQB6dgszcF8f0Z_-WDZOtTbrWbomYYvx1QjNtx3oS_ADR1xtKmjaEi7DP0nE94DMKDnFqMODjmIPzRAfFkNGrBDe1htF5n-03DJO-8w48ewFZOxWG0fTyRmV799rd-VQXeUpQCPh5ucxEOQvxOq7jKB2FyLXwm0l6Y9ig [following]
--2020-11-29 07:22:14--  https://developer.download.nvidia.com/compute/cuda/9.1/secure/Prod/local_installers/cuda-repo-ubuntu1704-9-1-local_9.1.85-1_amd64.deb?WkPGzPsRxBBT_nBljiVleNNiWH7s74QrdAQ15DlR83zbRNLQB6dgszcF8f0Z_-WDZOtTbrWbomYYvx1QjNtx3oS_ADR1xtKmjaEi7DP0nE94DMKDnFqMODjmIP

In [ ]:
!ls

cuda-repo-ubuntu1704-9-1-local_9.1.85-1_amd64  sample_data


In [ ]:
!dpkg -i cuda-repo-ubuntu1704-9-1-local_9.1.85-1_amd64

Selecting previously unselected package cuda-repo-ubuntu1704-9-1-local.
(Reading database ... 144793 files and directories currently installed.)
Preparing to unpack cuda-repo-ubuntu1704-9-1-local_9.1.85-1_amd64 ...
Unpacking cuda-repo-ubuntu1704-9-1-local (9.1.85-1) ...
Setting up cuda-repo-ubuntu1704-9-1-local (9.1.85-1) ...


In [ ]:
!ls /var/

backups  colab		      lib    lock  mail  run	tmp
cache	 cuda-repo-9-1-local  local  log   opt	 spool


In [ ]:
!ls /var/cuda-repo-9-1-local  | grep .pub

7fa2af80.pub


In [ ]:
!apt-key add /var/cuda-repo-9-1-local/7fa2af80.pub

OK


In [ ]:
!apt-get update

Get:1 file:/var/cuda-repo-9-1-local  InRelease
Ign:1 file:/var/cuda-repo-9-1-local  InRelease
Get:2 file:/var/cuda-repo-9-1-local  Release [574 B]
Get:2 file:/var/cuda-repo-9-1-local  Release [574 B]
Get:3 file:/var/cuda-repo-9-1-local  Release.gpg [819 B]
Get:3 file:/var/cuda-repo-9-1-local  Release.gpg [819 B]
Hit:4 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:5 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:6 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic InRelease [15.9 kB]
Get:7 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/ InRelease [3,626 B]
Get:8 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic InRelease [21.3 kB]
Get:9 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:10 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:11 file:/var/cuda-repo-9-1-local  Packages [19.1 kB]
Ign:12 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRel

In [ ]:
!apt-get install cuda-9-1

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  cuda-command-line-tools-9-1 cuda-compiler-9-1 cuda-cublas-9-1
  cuda-cublas-dev-9-1 cuda-cudart-9-1 cuda-cudart-dev-9-1 cuda-cufft-9-1
  cuda-cufft-dev-9-1 cuda-cuobjdump-9-1 cuda-cupti-9-1 cuda-curand-9-1
  cuda-curand-dev-9-1 cuda-cusolver-9-1 cuda-cusolver-dev-9-1
  cuda-cusparse-9-1 cuda-cusparse-dev-9-1 cuda-demo-suite-9-1
  cuda-documentation-9-1 cuda-driver-dev-9-1 cuda-gdb-9-1
  cuda-gpu-library-advisor-9-1 cuda-libraries-9-1 cuda-libraries-dev-9-1
  cuda-license-9-1 cuda-memcheck-9-1 cuda-misc-headers-9-1 cuda-npp-9-1
  cuda-npp-dev-9-1 cuda-nsight-9-1 cuda-nvcc-9-1 cuda-nvdisasm-9-1
  cuda-nvgraph-9-1 cuda-nvgraph-dev-9-1 cuda-nvml-dev-9-1 cuda-nvprof-9-1
  cuda-nvprune-9-1 cuda-nvrtc-9-1 cuda-nvrtc-dev-9-1 cuda-nvtx-9-1
  cuda-nvvp-9-1 cuda-runtime-9-1 cuda-samples-9-1 cuda-toolkit-9-1
  cuda-tools-9-1 cuda-visual-tools-9-1
Th

## Install [PyTorch](https://pytorch.org/) with Cuda 9.1 support

In [ ]:
!nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:07:56_CDT_2017
Cuda compilation tools, release 9.1, V9.1.85


In [ ]:
!pip install torch==0.4.0
#!pip install torchvision

     |████████████████████████████████| 484.0MB 30kB/s 
ERROR: torchvision 0.8.1+cu101 has requirement torch==1.7.0, but you'll have torch 0.4.0 which is incompatible.
ERROR: fastai 1.0.61 has requirement torch>=1.0.0, but you'll have torch 0.4.0 which is incompatible.
  Found existing installation: torch 1.7.0+cu101
    Uninstalling torch-1.7.0+cu101:
      Successfully uninstalled torch-1.7.0+cu101


In [ ]:
!git clone https://github.com/ajithvallabai/planercnn_outdoorimages

Cloning into 'planercnn_outdoorimages'...
remote: Enumerating objects: 196, done.
remote: Counting objects: 100% (196/196), done.
remote: Compressing objects: 100% (159/159), done.
remote: Total 196 (delta 40), reused 184 (delta 31), pack-reused 0
Receiving objects: 100% (196/196), 9.36 MiB | 3.34 MiB/s, done.
Resolving deltas: 100% (40/40), done.


In [ ]:
cd planercnn_outdoorimages/

/content/planercnn_outdoorimages


In [ ]:
!pip install -r requirements.txt

     |████████████████████████████████| 430kB 10.8MB/s 
     |████████████████████████████████| 13.9MB 22.7MB/s 
     |████████████████████████████████| 25.4MB 1.6MB/s 
     |████████████████████████████████| 25.3MB 52.8MB/s 
     |████████████████████████████████| 519.5MB 32kB/s 
     |████████████████████████████████| 51kB 7.4MB/s 
ERROR: umap-learn 0.4.6 has requirement numpy>=1.17, but you'll have numpy 1.15.4 which is incompatible.
ERROR: torchvision 0.8.1+cu101 has requirement torch==1.7.0, but you'll have torch 0.4.1 which is incompatible.
ERROR: tensorflow 2.3.0 has requirement numpy<1.19.0,>=1.16.0, but you'll have numpy 1.15.4 which is incompatible.
ERROR: spacy 2.2.4 has requirement tqdm<5.0.0,>=4.38.0, but you'll have tqdm 4.28.1 which is incompatible.
ERROR: rpy2 3.2.7 has requirement cffi>=1.13.1, but you'll have cffi 1.11.5 which is incompatible.
ERROR: plotnine 0.6.0 has requirement numpy>=1.16.0, but you'll have numpy 1.15.4 which is incompatible.
ERROR: fbprophet 0.7.

In [ ]:
!ls

cuda-repo-ubuntu1704-9-1-local_9.1.85-1_amd64  sample_data
planercnn_outdoorimages


In [ ]:
# !pip install torch==0.4.0

In [ ]:
!ls

cuda-repo-ubuntu1704-9-1-local_9.1.85-1_amd64  sample_data
planercnn_outdoorimages


In [ ]:
cd planercnn_outdoorimages/

/content/planercnn_outdoorimages


In [ ]:
!ls /usr/local/cuda-9.1

bin	include    libnvvp	     nvml    samples  targets
doc	lib64	   LICENSE	     nvvm    share    tools
extras	libnsight  nsightee_plugins  README  src      version.txt


In [ ]:
!export CUDA_PATH=/usr/local/cuda-9.1/

In [ ]:
# cd nms/src/cuda/

In [ ]:
# !ls

In [ ]:
!sudo apt-get update && \
sudo apt-get install build-essential software-properties-common -y && \
sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y && \
sudo apt-get update && \
sudo apt-get install gcc-5 g++-5 -y && \
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 50 --slave /usr/bin/g++ g++ /usr/bin/g++-5 && \
gcc -v

Get:1 file:/var/cuda-repo-9-1-local  InRelease
Ign:1 file:/var/cuda-repo-9-1-local  InRelease
Get:2 file:/var/cuda-repo-9-1-local  Release [574 B]
Get:2 file:/var/cuda-repo-9-1-local  Release [574 B]
Hit:3 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic InRelease
Hit:4 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:5 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:6 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic InRelease
Hit:7 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:8 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/ InRelease
Hit:9 http://security.ubuntu.com/ubuntu bionic-security InRelease
Ign:11 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Ign:12 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Hit:13 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release
Hit:14 https://developer.downlo

In [ ]:
!gcc --version

gcc (Ubuntu 5.5.0-12ubuntu1) 5.5.0 20171010
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.



In [ ]:
!sudo apt-get install gcc-5 g++-5 g++-5-multilib gfortran-5

Reading package lists... Done
Building dependency tree       
Reading state information... Done
g++-5 is already the newest version (5.5.0-12ubuntu1).
gcc-5 is already the newest version (5.5.0-12ubuntu1).
The following additional packages will be installed:
  gcc-10-base gcc-5-multilib gcc-6-base gcc-7-multilib gcc-multilib lib32asan2
  lib32asan4 lib32atomic1 lib32cilkrts5 lib32gcc-5-dev lib32gcc-7-dev
  lib32gomp1 lib32itm1 lib32mpx0 lib32mpx2 lib32quadmath0 lib32stdc++-5-dev
  lib32ubsan0 libc6-dev-i386 libc6-dev-x32 libc6-x32 libgfortran-5-dev
  libgfortran3 libx32asan2 libx32asan4 libx32atomic1 libx32cilkrts5
  libx32gcc-5-dev libx32gcc-7-dev libx32gcc-s1 libx32gcc1 libx32gomp1
  libx32itm1 libx32quadmath0 libx32stdc++-5-dev libx32stdc++6 libx32ubsan0
Suggested packages:
  lib32stdc++6-5-dbg libx32stdc++6-5-dbg gfortran-5-multilib gfortran-5-doc
  libgfortran3-dbg
The following NEW packages will be installed:
  g++-5-multilib gcc-10-base gcc-5-multilib gcc-6-base gcc-7-multilib
 

In [ ]:
!sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 50 --slave /usr/bin/g++ g++ /usr/bin/g++-5

In [ ]:
!sudo update-alternatives --config gcc

There is only one alternative in link group gcc (providing /usr/bin/gcc): /usr/bin/gcc-5
Nothing to configure.


In [ ]:
!gcc --version

gcc (Ubuntu 5.5.0-12ubuntu1) 5.5.0 20171010
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.



In [ ]:
#!nvcc -c -o nms_kernel.cu.o nms_kernel.cu -x cu -Xcompiler -fPIC -arch=sm_60

In [ ]:
!ls

anchors		      genrate_3dmodel	       README.md
config.py	      LICENSE.md	       requirements.txt
data_prep	      models		       roialign
datasets	      myscreenshot.png	       train_planercnn_custom.py
datasets_custom       nms		       train_planercnn.py
demostore	      options.py	       tree.md
evaluate_orginal.py   output.png	       utils.py
evaluate_realtime.py  planercnn_outdoorimages  visualize_utils.py
evaluate_utils.py     plane_utils.py	       write_ply_planenet.py
example_images	      __pycache__


In [ ]:
#cd ../../

In [ ]:
#!python build.py

In [ ]:
#cd ..

In [ ]:
#cd roialign/roi_align/src/cuda/

In [ ]:
#!nvcc -c -o crop_and_resize_kernel.cu.o crop_and_resize_kernel.cu -x cu -Xcompiler -fPIC -arch=sm_60

In [ ]:
#cd ../../

In [ ]:
#!python build.py

In [ ]:
#cd ../..

In [ ]:
#cd ..

In [ ]:
#!ls

In [ ]:
#!pip install torch==0.4.1

In [ ]:
!pip install pyvista

     |████████████████████████████████| 1.2MB 14.1MB/s 
     |████████████████████████████████| 153kB 42.4MB/s 
     |████████████████████████████████| 103.4MB 73kB/s 


In [ ]:
!python evaluate_orginal.py --methods=f --suffix=warping_refine --dataset=inference --customDataFolder=example_images

achor type---- normal
the number of images 3
  0% 0/3 [00:00<?, ?it/s]/content/planercnn_outdoorimages/models/model.py:1473: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  nn.init.xavier_uniform(m.weight)
Traceback (most recent call last):
  File "evaluate_orginal.py", line 671, in <module>
    evaluate(args)
  File "evaluate_orginal.py", line 546, in evaluate
    detectors.append(('final', PlaneRCNNDetector(options, config, modelType='final')))
  File "evaluate_orginal.py", line 73, in __init__
    self.model.load_state_dict(torch.load(checkpoint_dir + '/checkpoint.pth'))
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoint/planercnn_normal_warping_refine/checkpoint.pth'



In [ ]:
!ls

anchors		      genrate_3dmodel	       README.md
config.py	      LICENSE.md	       requirements.txt
data_prep	      models		       roialign
datasets	      myscreenshot.png	       test
datasets_custom       nms		       train_planercnn_custom.py
demostore	      options.py	       train_planercnn.py
evaluate_orginal.py   output.png	       tree.md
evaluate_realtime.py  planercnn_outdoorimages  utils.py
evaluate_utils.py     plane_utils.py	       visualize_utils.py
example_images	      __pycache__	       write_ply_planenet.py


In [ ]:
cd data_prep/

/content/planercnn_outdoorimages/data_prep


In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
import os

In [ ]:
# os.chdir("/content/gdrive/MyDrive/computer_vision/capstone_project/planercnn_customimages-master/")

In [ ]:
# !mkdir Data/scans/scene0003_02/

In [ ]:
# !ls "/content/gdrive/My Drive/skunkworks/custom_dataset_files"

In [ ]:
# !cp "/content/gdrive/My Drive/skunkworks/custom_dataset_files/annotation.zip" "Data/scans/scene0003_02/"

In [ ]:
# !cp "/content/gdrive/My Drive/skunkworks/custom_dataset_files/frames.zip" "Data/scans/scene0003_02/"

In [ ]:
# !cp "/content/gdrive/My Drive/skunkworks/custom_dataset_files/scene0003_02.txt" "Data/scans/scene0003_02/"

In [ ]:
# cd Data/scans/scene0003_02/

In [ ]:
# !unzip annotation.zip

In [ ]:
# !mv annotation/segmentation_renamed annotation/segmentation

In [ ]:
# !ls

In [ ]:
# !unzip frames.zip

In [ ]:
# !ls

In [ ]:
# cd ..

In [ ]:
# !cp "/content/gdrive/My Drive/skunkworks/otherfolders.zip" "Data/scans/"

In [ ]:
# cd Data/scans

In [ ]:
# !ls

In [ ]:
# mv otherfolders.zip ../

In [ ]:
# cd ..

In [ ]:
# !unzip otherfolders.zip

In [ ]:
# !ls otherfolders

In [ ]:
# !cp -r otherfolders/ScanNet "./"

In [ ]:
# !ls

In [ ]:
# !cp -r otherfolders/anchor_planes_N.npy "./"

In [ ]:
# !cp -r otherfolders/invalid_indices_test.txt "./"

In [ ]:
# !cp -r otherfolders/invalid_indices_train.txt "./"

In [ ]:
# !cp -r otherfolders/tasks "./"

In [ ]:
# !ls

In [ ]:
# cd ../..

In [ ]:
cd ..

/content/planercnn_outdoorimages


In [ ]:
%%writefile exect1.sh

fileId=1o2wZG0swF-HImZbQGPC7cHONkCThFVQZ
fileName=checkpoint.zip
curl -sc /tmp/cookie "https://drive.google.com/uc?export=download&id=${fileId}" > /dev/null
code="$(awk '/_warning_/ {print $NF}' /tmp/cookie)"  
curl -Lb /tmp/cookie "https://drive.google.com/uc?export=download&confirm=${code}&id=${fileId}" -o ${fileName}

Writing exect1.sh


In [ ]:
!sh exect1.sh

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   408    0   408    0     0   2103      0 --:--:-- --:--:-- --:--:--  2103
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  250M    0  250M    0     0  38.7M      0 --:--:--  0:00:06 --:--:-- 50.2M


In [ ]:
!ls

anchors		      exect1.sh		       README.md
checkpoint.zip	      genrate_3dmodel	       requirements.txt
config.py	      LICENSE.md	       roialign
data_prep	      models		       test
datasets	      myscreenshot.png	       train_planercnn_custom.py
datasets_custom       nms		       train_planercnn.py
demostore	      options.py	       tree.md
evaluate_orginal.py   output.png	       utils.py
evaluate_realtime.py  planercnn_outdoorimages  visualize_utils.py
evaluate_utils.py     plane_utils.py	       write_ply_planenet.py
example_images	      __pycache__


In [ ]:
!unzip checkpoint.zip

Archive:  checkpoint.zip
   creating: planercnn_normal_warping_refine/
  inflating: planercnn_normal_warping_refine/checkpoint_refine.pth  
  inflating: planercnn_normal_warping_refine/checkpoint.pth  


In [ ]:
!mkdir checkpoint

In [ ]:
ls

anchors/               nms/
checkpoint/            options.py
checkpoint.zip         output.png
config.py*             planercnn_normal_warping_refine/
data_prep/             planercnn_outdoorimages/
datasets/              plane_utils.py*
datasets_custom/       __pycache__/
demostore/             README.md
evaluate_orginal.py    requirements.txt*
evaluate_realtime.py*  roialign/
evaluate_utils.py*     test/
example_images/        train_planercnn_custom.py
exect1.sh              train_planercnn.py*
genrate_3dmodel/       tree.md
LICENSE.md             utils.py*
models/                visualize_utils.py*
myscreenshot.png       write_ply_planenet.py


In [ ]:
cd /content/planercnn_outdoorimages/

/content/planercnn_outdoorimages


In [ ]:
!mv planercnn_normal_warping_refine checkpoint/ 

In [ ]:
# cd planercnn_outdoorimages/

In [ ]:
#!mv checkpoint.zip checkpoint/

In [ ]:
# cd checkpoint/

In [ ]:
#!unzip checkpoint.zip

In [ ]:
#cd ..

In [ ]:
#cd planercnn/

In [ ]:
!mkdir "data_prep/Data/scans"

In [ ]:
!ls

anchors		      example_images	       __pycache__
checkpoint	      exect1.sh		       README.md
checkpoint.zip	      genrate_3dmodel	       requirements.txt
config.py	      LICENSE.md	       roialign
data_prep	      models		       test
datasets	      myscreenshot.png	       train_planercnn_custom.py
datasets_custom       nms		       train_planercnn.py
demostore	      options.py	       tree.md
evaluate_orginal.py   output.png	       utils.py
evaluate_realtime.py  planercnn_outdoorimages  visualize_utils.py
evaluate_utils.py     plane_utils.py	       write_ply_planenet.py


In [ ]:
!cp "/content/gdrive/MyDrive/computer_vision/skunkworks/24112020_scene0003_02.zip" "data_prep/Data/scans/"

In [ ]:
cd data_prep/Data/scans/


/content/planercnn_outdoorimages/data_prep/Data/scans


In [ ]:
# !mkdir scan

In [ ]:
# mv "24112020_scene0003_02.zip" scan/

In [ ]:
# cd scan

In [ ]:
!unzip 24112020_scene0003_02.zip

Streaming output truncated to the last 5000 lines.
  inflating: scene0003_02/frames/pose/533.txt  
  inflating: scene0003_02/frames/pose/534.txt  
  inflating: scene0003_02/frames/pose/536.txt  
  inflating: scene0003_02/frames/pose/537.txt  
  inflating: scene0003_02/frames/pose/538.txt  
  inflating: scene0003_02/frames/pose/539.txt  
  inflating: scene0003_02/frames/pose/540.txt  
  inflating: scene0003_02/frames/pose/541.txt  
  inflating: scene0003_02/frames/pose/543.txt  
  inflating: scene0003_02/frames/pose/544.txt  
  inflating: scene0003_02/frames/pose/545.txt  
  inflating: scene0003_02/frames/pose/546.txt  
  inflating: scene0003_02/frames/pose/547.txt  
  inflating: scene0003_02/frames/pose/549.txt  
  inflating: scene0003_02/frames/pose/551.txt  
  inflating: scene0003_02/frames/pose/552.txt  
  inflating: scene0003_02/frames/pose/553.txt  
  inflating: scene0003_02/frames/pose/555.txt  
  inflating: scene0003_02/frames/pose/558.txt  
  inflating: scene0003_02/frames/pose

In [ ]:
cd ..

/content/planercnn_outdoorimages/data_prep/Data


In [ ]:
cd ../..

/content/planercnn_outdoorimages


In [ ]:
cd data_prep/Data

/content/planercnn_outdoorimages/data_prep/Data


In [ ]:
!rm -r ScanNet

In [ ]:
!git clone https://github.com/ScanNet/ScanNet.git

Cloning into 'ScanNet'...
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 1440 (delta 4), reused 5 (delta 0), pack-reused 1427
Receiving objects: 100% (1440/1440), 7.72 MiB | 10.57 MiB/s, done.
Resolving deltas: 100% (498/498), done.


In [ ]:
cd ../..

/content/planercnn_outdoorimages


In [ ]:
!ls data_prep/Data/scans/scene0003_02/

annotation  frames  scene0003_02.txt


In [ ]:
!ls data_prep/Data/scans/scene0003_02/

annotation  frames  scene0003_02.txt


In [ ]:
cd /content/planercnn_outdoorimages/

/content/planercnn_outdoorimages


In [ ]:
!python train_planercnn.py --restore=0 --suffix=warping_refine --dataFolder="data_prep/Data"

keyname=planercnn_normal_warping_refine task=train started
achor type---- normal
[[ 7.21337371e-02 -4.70870854e-02  8.37980522e-01]
 [ 4.87355142e-01 -7.17826291e-04  1.70417877e-01]
 [-1.94980880e-01 -1.81253737e-02  8.03455137e-01]
 [ 4.44071273e-02  1.88602029e+00  2.66851526e-01]
 [ 5.51112079e-01 -7.61530571e-03 -4.31234863e-02]
 [ 7.67863927e-02 -1.10999903e-02  1.04032826e+00]
 [ 2.61500389e-01 -4.78849513e-03  5.04700680e-02]
 [-1.59022463e-02  1.97024238e+00  2.96101087e-02]
 [ 2.91635867e-01  3.51360714e-03 -2.00631680e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 8.26088340e-01 -1.34148901e-02 -2.71477500e-02]
 [-3.57411066e-02  2.01167001e+00  4.88067368e-02]
 [ 7.08732229e-01 -1.21720207e-01  1.74088124e+00]
 [ 2.95308416e-01 -8.75964323e-02  1.25566744e+00]
 [ 8.93865650e-01  1.58832837e+00  1.50642714e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 3.34837733e-02  2.90334710e+00  7.00093450e-02]
 [ 2.99221016e+00  4.98655225e-02 -5.68913191e-02]
 

In [ ]:
!python train_planercnn_custom.py --restore=0 --suffix=warping_refine --dataFolder="data_prep/Data"

keyname=planercnn_normal_warping_refine task=train started
achor type---- normal
planes [[ 7.21337371e-02 -4.70870854e-02  8.37980522e-01]
 [ 4.87355142e-01 -7.17826291e-04  1.70417877e-01]
 [-1.94980880e-01 -1.81253737e-02  8.03455137e-01]
 [ 4.44071273e-02  1.88602029e+00  2.66851526e-01]
 [ 5.51112079e-01 -7.61530571e-03 -4.31234863e-02]
 [ 7.67863927e-02 -1.10999903e-02  1.04032826e+00]
 [ 2.61500389e-01 -4.78849513e-03  5.04700680e-02]
 [-1.59022463e-02  1.97024238e+00  2.96101087e-02]
 [ 2.91635867e-01  3.51360714e-03 -2.00631680e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 8.26088340e-01 -1.34148901e-02 -2.71477500e-02]
 [-3.57411066e-02  2.01167001e+00  4.88067368e-02]
 [ 7.08732229e-01 -1.21720207e-01  1.74088124e+00]
 [ 2.95308416e-01 -8.75964323e-02  1.25566744e+00]
 [ 8.93865650e-01  1.58832837e+00  1.50642714e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 3.34837733e-02  2.90334710e+00  7.00093450e-02]
 [ 2.99221016e+00  4.98655225e-02 -5.68913191

In [ ]:
# cp -rf /content/planercnn_outdoorimages/ /content/gdrive/MyDrive/computer_vision/capstone_project/

In [ ]:
ls /content/gdrive/MyDrive/computer_vision/capstone_project/planercnn_outdoorimages/

anchors/              example_images/           __pycache__/
checkpoint/           exect1.sh                 README.md
checkpoint.zip        genrate_3dmodel/          requirements.txt
config.py             LICENSE.md                roialign/
data_prep/            models/                   test/
datasets/             myscreenshot.png          train_planercnn_custom.py
datasets_custom/      nms/                      train_planercnn.py
demostore/            options.py                tree.md
evaluate_orginal.py   output.png                utils.py
evaluate_realtime.py  planercnn_outdoorimages/  visualize_utils.py
evaluate_utils.py     plane_utils.py            write_ply_planenet.py


In [ ]:
#-----------------------------

In [ ]:
!pip install torch==0.4.1

  Using cached https://files.pythonhosted.org/packages/49/0e/e382bcf1a6ae8225f50b99cc26effa2d4cc6d66975ccf3fa9590efcbedce/torch-0.4.1-cp36-cp36m-manylinux1_x86_64.whl
ERROR: torchvision 0.8.1+cu101 has requirement torch==1.7.0, but you'll have torch 0.4.1 which is incompatible.
ERROR: fastai 1.0.61 has requirement torch>=1.0.0, but you'll have torch 0.4.1 which is incompatible.
  Found existing installation: torch 0.4.0
    Uninstalling torch-0.4.0:
      Successfully uninstalled torch-0.4.0


In [ ]:
import numpy as np
import torch
MEAN_PIXEL = np.array([123.7, 116.8, 103.9])
MT=torch.from_numpy(MEAN_PIXEL.astype(np.float32)).cuda()

In [ ]:
import torch

In [ ]:
cd ..

/content/planercnn


In [ ]:
!ls

anchor_planes_N.npy	  invalid_indices_train.txt  scene0190_00
invalid_indices_test.txt  ScanNet		     tasks


In [ ]:
#############--------------END of training--------------------------------------------------